[package]
name = "dd40_texture_pack"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true, default-features = false, features = [
    "bevy_asset",
    "bevy_image",
    "bevy_log",
    "bevy_render",
    "bevy_state",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"
image = { version = "0.25", default-features = false, features = ["png"] }
dd40_core = { workspace = true }
dd40_config = { workspace = true }
dd40_texture_core = { workspace = true }

[dev-dependencies]
tempfile = "3.10"
toml = "0.8"

[lints]
workspace = true
