[package]
name = "dd40_loose_item_core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true, default-features = false }
dd40_core = { workspace = true }
dd40_item_core = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[lints]
workspace = true
