[package]
name = "dd40_loose_item_render"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true, default-features = false, features = [
    "bevy_pbr",
    "bevy_render",
    "bevy_asset",
] }
dd40_core = { workspace = true }
dd40_item_core = { workspace = true }
dd40_loose_item_core = { workspace = true }
